"""message table

Revision ID: 8a6480d0e0c9
Revises: 
Create Date: 2020-03-14 21:14:36.461461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a6480d0e0c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_author'), 'message', ['author'], unique=False)
    op.create_table('visitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cookie', sa.String(length=128), nullable=True),
    sa.Column('first_visit', sa.Integer(), nullable=True),
    sa.Column('counter', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitor_cookie'), 'visitor', ['cookie'], unique=True)
    op.create_index(op.f('ix_visitor_first_visit'), 'visitor', ['first_visit'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visitor_first_visit'), table_name='visitor')
    op.drop_index(op.f('ix_visitor_cookie'), table_name='visitor')
    op.drop_table('visitor')
    op.drop_index(op.f('ix_message_author'), table_name='message')
    op.drop_table('message')
    # ### end Alembic commands ###
